config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new

  resources :solr_document, only: [:show], path: '/record', controller: 'records' do
    concerns :exportable
    get 'fulltext', to: 'records#fulltext'
    get 'presentation/manifest', to: 'records#presentation_manifest'
    get 'harmful_content', to: 'records#harmful_content'
  end

  resource :records, only: %i[index show] do
    get 'map', to: 'map', as: 'map'
    concerns :searchable
    concerns :range_searchable
    collection do
      get 'suggest/:facet_name', to: 'records#suggest', as: 'suggest_facet', defaults: { format: 'json' }
    end
  end

  # so related routes are available with the *_catalog_url that BL expects in addition to *_record_url
  resource :records, only:[], as: :catalog do
    concerns :searchable
  end

  get '/collection/:collection_record_id', to: 'records#index', as: 'collection_home'

  if FeatureFlags.enabled? :serials
    get '/serial/:serial_record_id', to: 'records#index', as: 'serial_home'
  else
    get '/serial/:serial_record_id', to: redirect {|path_params, _request|
      TemporaryRedirectService.legacy_route_for_serial(path_params[:serial_record_id])
    }
  end
  get '/serials/:serial_record_id', to: redirect('/serial/%{serial_record_id}')

  resource :collections, only: [:index] do
    get 'map', to: 'map', as: 'map'
    concerns :searchable
    concerns :range_searchable
    member do
      get(
        '/:collection_record_id/:collection_resource_slug',
        to: 'collection_resources#show',
        as: 'collection_resource'
      )
    end
  end

  resource :serials, only: %i[index] do
    concerns :searchable
    concerns :range_searchable
  end

  get '/collections/:collection_slug', to: 'records#index'

  resource :institutions, only: %i[index], path: '/institutions(/:first_char)', first_char: /[a-zA-Z]|0-9/, controller: 'institutions' do
    concerns :searchable
  end

  resources :institution_solr_documents, only: [:show], path: '/institutions/', controller: 'institutions' do
    concerns :exportable
  end

  resources :collection_solr_documents, only: [:show], path: '/collections/', controller: 'collections' do
    concerns :exportable
  end

  resources :serial_solr_documents, only: [:show], path: '/serials/', controller: 'serials' do
    concerns :exportable
  end

  get '/search', to: 'advanced#index', as: 'search'
  get '/counties', to: 'counties#index', as: 'counties'

  get '/iiif-viewer', to: 'iiif_viewer#iiif_viewer', as: 'iiif_viewer'
  get '/iiif-embeddable', to: 'iiif_viewer#embeddable_iiif_viewer', as: 'embeddable_iiif_viewer'

  resources :bookmarks do
    concerns :exportable
    collection do
      delete 'clear'
    end
  end

  namespace :teach do
    get 'using-materials'
  end

  namespace :participate do
    get 'contribute'
    get 'nominate'
    get 'harmful_content'
    get 'partner-services'
    post 'nomination'
  end

  namespace :about do
    get 'mission'
    get 'policy'
    get 'partners-sponsors'
    get 'api'
    get 'harmful-content'
    get 'harmful-content-form'
    post 'harmful_content_submit'
  end

  namespace :help do
    get 'search'
    get 'refine-items'
    get 'refine-collections'
    get 'map'
  end

  get '/contact(/:formtype)', to: 'contact#index', formtype: /|dlg|crdl|ghnp/, as: 'contact'

  get '/id::record_id', to: redirect('/record/%{record_id}'), status: 301

  get '/*do_tag', do_tag: /do(?:-[a-z0-9-]+)?:[a-z0-9,_-]+/, to: redirect { |path_params, _req|
    if (m=path_params[:do_tag].match /^do(?<alt>-[a-z0-9-]+)?:(?<record_id>[a-z0-9,_-]+)$/)
      "https://dlg.galileo.usg.edu/do#{m[:alt]}:#{m[:record_id]}"
    end
  }

  root to: 'homepage#index'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/views/shared/_facet_sort_group.html.erb
<div class="btn-group facet-sort-group" role="group" aria-label="Sort Options">
  <%= link_to t('search.facets.sort.az'), sort_params.merge({p => 'index'}), class: "facet-sort-link btn #{active_facet_sort(p, 'index')}" %>
  <%= link_to t('search.facets.sort.count'), sort_params.merge({p => 'count'}), class: "facet-sort-link btn #{active_facet_sort(p, 'count')}" %>
</div>

app/views/shared/_feedback.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= link_to t('feedback.feature_feedback_button.label'), t('external_links.contact'), class: 'btn btn-default', target: '_blank', title: t('feedback.feature_feedback_button.popup_text'), data: { toggle: 'tooltip', placement: 'left' } %>
  </div>
</div>

app/views/shared/_flash_messages.html.erb
<section id="flash-message">
  <div class="container-xl">
    <div class="row">
      <div class="col-lg-12">
        <div id="main-flashes">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_footer.html.erb
<footer class="footer" role="contentinfo">
  <div class="container-xl">
    <div class="row">
      <div class="col-12 col-md-3 pull-left">
        <ul class="footer-nav">
          <li><%= link_to t('menu.home'), root_path %></li>
          <li><%= link_to t('menu.about'), about_mission_path  %></li>
          <li><%= link_to t('menu.accessibility'), t('external_links.accessibility')  %></li>
          <li><a href="https://dp.la" target="_blank" rel="noopener noreferrer">Digital Public Library of America</a></li>
          <li><%= link_to t('external_links.labels.ghnp'), t('external_links.dlg.ghnp') %></li>
          <li><%= link_to t('external_links.labels.crdl'), t('external_links.dlg.crdl') %></li>
        </ul>
      </div>
      <div class="col-12 col-md-6 ">
        <p class="harmful-content"><%= t('footer.harmful_content') %> <strong><%= link_to 'Read our statement on potentially harmful content.', about_harmful_content_path %></strong></p>
        <p class="text-center"><%= t('footer.galileo') %><br>
          <%= t('footer.copyright', year: DateTime.now.year) %></p>
      </div>
      <div class="col-12 col-md-3 pull-right">
        <ul class="social-icons ">
          <li><%= link_to '<i class="fa fa-facebook-square fa-2x" aria-hidden="true"></i>'.html_safe, t('external_links.dlg.facebook'), { title: "DLG's Facebook page" } %></li>
          <li><%= link_to '<i class="fa fa-rss-square fa-2x" aria-hidden="true"></i>'.html_safe, t('external_links.dlg.blog'), { title: 'The DLG Blog' } %></li>
          <li><%= link_to '<i class="fa fa-envelope-square fa-2x" aria-hidden="true"></i>'.html_safe, contact_path, { title: t('contact.header'), rel: 'noopener' } %></li>
        </ul>
        <div>
        <%= link_to 'https://www.familytreemagazine.com/best-state-genealogy-websites/' do %>
          <%= image_tag 'familytree_2021.png', :class => 'img-fluid, awardImg', alt: 'FamilyTree magazine 2020 best State websites award'%>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header_navbar.html.erb
<%= outage_banner 'October 22, 2024', 'October 27, 2024', 'The DLG site may be unavailable Sunday, October 27th, due to network maintenance.' %>

<header class="header">
  <div class="container-xl">
    <div class="row">
      <div class="col-sm-12">
        <div class="d-flex align-items-center justify-content-between">
          <a href="<%= root_path %>"><img class="logo-dlg img-fluid" src="<%= asset_path 'logo-dlg.svg' %>" alt="Digital Library of Georgia, Sharing Georgia's History &amp; Culture Online"></a>
          <ul class="social-icons mt-3">
            <li><%= link_to '<i class="fa fa-facebook-square fa-2x" aria-hidden="true"></i>'.html_safe, t('external_links.dlg.facebook'), { title: "DLG's Facebook page" } %></li>
            <li><%= link_to '<i class="fa fa-rss-square fa-2x" aria-hidden="true"></i>'.html_safe, t('external_links.dlg.blog'), { title: 'The DLG Blog' } %></li>
            <li><%= link_to '<i class="fa fa-envelope-square fa-2x" aria-hidden="true"></i>'.html_safe, contact_path, { title: t('contact.header'), rel: 'noopener' } %></li>
          </ul>
          <div class="additional_logos">
            <a href="<%= t('external_links.galileo') %>" rel="noopener" target="_blank" class="mr-2">
              <img class="logo-galileo img-fluid" src="<%= asset_path 'logo-galileo.svg' %>" alt="GALILEO, Georgia's Virtual Library, An Initiative of the University System of Georgia">
            </a>
            <a href="<%= t('external_links.uga_library') %>" rel="noopener" target="_blank">
              <img class="logo-uga-library img-fluid" src="<%= asset_path 'logo-ugalibs.svg' %>" alt="University of Georgia, University Libraries">
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="banner">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 h1">
          <a href="<%= root_path %>"><%= t('external_links.labels.dlg') %></a>
        </div>
      </div>
    </div>
  </div>
</header>
<nav class="navbar navbar-light navbar-default navbar-expand-lg" role="navigation" aria-label="Site Navigation">
  <div class="container-xl justify-content-end">
    <button class="navbar-toggler pull-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="<%= root_path %>"><%= t('menu.home') %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= search_path %>"><%= t('menu.search') %></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="exploreNavbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= t('menu.explore') %>
          </a>
          <div class="dropdown-menu" aria-labelledby="exploreNavbarDropdown">
            <a class="dropdown-item" href="<%= search_records_path %>"><%= t('menu.explore_sub.items') %></a>
            <a class="dropdown-item" href="<%= search_collections_path %>"><%= t('menu.explore_sub.collections') %></a>
            <% if FeatureFlags.enabled? :serials %>
              <a class="dropdown-item" href="<%= search_serials_path %>"><%= t('menu.explore_sub.serials') %></a>
            <% end %>
            <a class="dropdown-item" href="<%= counties_path %>"><%= t('menu.explore_sub.counties') %></a>
            <a class="dropdown-item" href="<%= search_institutions_path %>"><%= t('menu.explore_sub.institutions') %></a>
            <a class="dropdown-item" href="<%= map_records_path %>"><%= t('menu.explore_sub.map') %></a>
            <a class="dropdown-item" href="/#featured-collections-heading"><%= t('menu.explore_sub.featured_collections')%></a>
            <a class="dropdown-item" href="<%= t('external_links.dlg.spotlight')%>"><%= t('external_links.labels.spotlight') %></a>
          </div>
        </li>
      </ul>
      <div class="nav navbar-nav navbar-right">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="teachNavbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= t('menu.teach') %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="teachNavbarDropdown">
              <a class="dropdown-item" href="<%= t('external_links.dlg.educator_resources') %>"><%= t('external_links.labels.educator_resources') %></a>
              <a class="dropdown-item" href="<%= t('external_links.national_history_day') %>"><%= t('external_links.labels.national_history_day') %></a>
              <a class="dropdown-item" href="<%= t('external_links.nge') %>"><%= t('external_links.labels.nge') %></a>
              <a class="dropdown-item" href="<%= t('external_links.dlg.georgia_exhibits') %>"><%= t('external_links.labels.georgia_exhibits') %></a>
              <a class="dropdown-item" href="<%= teach_using_materials_path %>"><%= t('external_links.labels.dlg_materials') %></a>
              <a class="dropdown-item" href="<%= freely_available_path %>"><%= t('external_links.labels.free_materials') %></a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="participateNavbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= t('menu.participate') %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="participateNavbarDropdown">
              <%= link_to 'ArchivesSpace Hosting', 'https://sites.google.com/view/dlg-docs/resources/programs-and-projects/archivesspace-hosting-pilot', class: "dropdown-item" %>
              <%= link_to 'Contribute Your Collections', participate_contribute_path, class: "dropdown-item" %>
              <%= link_to 'Nominate Collections', participate_nominate_path, class: "dropdown-item" %>
              <a class="dropdown-item" href="https://sites.google.com/view/dlg-docs/resources/programs-and-projects/subgranting-program">Subgranting Program</a>
              <%= link_to 'Services for Partners', participate_partner_services_path, class: "dropdown-item" %>
              <a class="dropdown-item" href="https://georgialibraries.org/archival-services/">Services for Public Libraries</a>
              <a class="dropdown-item" href="https://sites.google.com/view/dlg-docs/">Documentation and reports</a>
              <a class="dropdown-item" href="https://sites.google.com/view/dlg-docs/">Presentations and Workshops</a>
              <a class="dropdown-item" href="https://sites.google.com/view/dlg-docs/resources/promotional-materials">Promotional Materials</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= t('external_links.donate') %>"><%= t('external_links.labels.donate') %></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="connectNavbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= t('menu.connect') %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="connectNavbarDropdown">
              <%= link_to t('contact.header'), contact_path, { title: t('contact.header'), rel: 'noopener', class: "dropdown-item" }  %>
              <%= link_to 'Blog', t('external_links.dlg.blog'), class: "dropdown-item"  %>
              <%= link_to 'Listserv', t('external_links.dlg.listserv'), class: "dropdown-item"  %>
              <a class="dropdown-item" href="https://goo.gl/Ua4S4n">Newsletter</a>
              <%= link_to 'Facebook', t('external_links.dlg.facebook'), class: "dropdown-item"  %>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="aboutNavbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= t('menu.about') %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="aboutNavbarDropdown">
              <%= link_to 'Harmful Content', about_harmful_content_path, class: "dropdown-item" %>
              <%= link_to 'Mission, Guiding Principles, and Goals', about_mission_path, class: "dropdown-item" %>
              <%= link_to 'Collection Development Policy', about_policy_path, class: "dropdown-item" %>
              <%= link_to 'DLG Partners and Sponsors', about_partners_sponsors_path, class: "dropdown-item" %>
              <%= link_to 'DLG and Me', "/#dlg-and-me-heading", class: "dropdown-item" %>
              <%= link_to 'DLG API', about_api_path, class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>
      </ul>
    </div>
  </div>
</nav>
<div class="search mb-4">
  <%= render_search_bar %>
</div>

app/views/shared/_search_form.html.erb
<div class="container-xl">
  <%= form_tag search_action, method: :get, class: 'search-query-form', role: 'search', 'aria-label': 'Search Form' do %>
    <div class="row">
      <div class="offset-lg-2 col-lg-8 searchbox">
        <div class="input-group input-group-lg">
          <label for="q" class="sr-only"><%= t('blacklight.search.form.search.sr_label') %></label>
          <input name="q" type="text" id="q" autocomplete="on" class="form-control" placeholder="<%= search_bar_placeholder %>" aria-label="Search <%= search_bar_placeholder %>">
          <input type="hidden" name="search_field" value="<%= search_type_key %>">
          <%= render_hash_as_hidden_fields(search_state.params_for_search.except(:q, :search_field, :qt, :page, :utf8)) %>
          <div class="input-group-append submit-btn">
            <button class="btn btn-primary" type="submit" title="Submit search">
              <i class="fa fa-search" aria-hidden="true"></i>
            </button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_survey_banner.html.erb
<div class="top-banner">
  <div class="container-xl">
    <div class="row">
      <a href="<%= t('external_links.contact') %>">Need some help?</a>
    </div>
  </div>
</div>