config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new

  resources :solr_document, only: [:show], path: '/record', controller: 'records' do
    concerns :exportable
    get 'fulltext', to: 'records#fulltext'
    get 'presentation/manifest', to: 'records#presentation_manifest'
    get 'harmful_content', to: 'records#harmful_content'
  end

  resource :records, only: %i[index show] do
    get 'map', to: 'map', as: 'map'
    concerns :searchable
    concerns :range_searchable
    collection do
      get 'suggest/:facet_name', to: 'records#suggest', as: 'suggest_facet', defaults: { format: 'json' }
    end
  end

  # so related routes are available with the *_catalog_url that BL expects in addition to *_record_url
  resource :records, only:[], as: :catalog do
    concerns :searchable
  end

  get '/collection/:collection_record_id', to: 'records#index', as: 'collection_home'

  if FeatureFlags.enabled? :serials
    get '/serial/:serial_record_id', to: 'records#index', as: 'serial_home'
  else
    get '/serial/:serial_record_id', to: redirect {|path_params, _request|
      TemporaryRedirectService.legacy_route_for_serial(path_params[:serial_record_id])
    }
  end
  get '/serials/:serial_record_id', to: redirect('/serial/%{serial_record_id}')

  resource :collections, only: [:index] do
    get 'map', to: 'map', as: 'map'
    concerns :searchable
    concerns :range_searchable
    member do
      get(
        '/:collection_record_id/:collection_resource_slug',
        to: 'collection_resources#show',
        as: 'collection_resource'
      )
    end
  end

  resource :serials, only: %i[index] do
    concerns :searchable
    concerns :range_searchable
  end

  get '/collections/:collection_slug', to: 'records#index'

  resource :institutions, only: %i[index], path: '/institutions(/:first_char)', first_char: /[a-zA-Z]|0-9/, controller: 'institutions' do
    concerns :searchable
  end

  resources :institution_solr_documents, only: [:show], path: '/institutions/', controller: 'institutions' do
    concerns :exportable
  end

  resources :collection_solr_documents, only: [:show], path: '/collections/', controller: 'collections' do
    concerns :exportable
  end

  resources :serial_solr_documents, only: [:show], path: '/serials/', controller: 'serials' do
    concerns :exportable
  end

  get '/search', to: 'advanced#index', as: 'search'
  get '/counties', to: 'counties#index', as: 'counties'

  get '/iiif-viewer', to: 'iiif_viewer#iiif_viewer', as: 'iiif_viewer'
  get '/iiif-embeddable', to: 'iiif_viewer#embeddable_iiif_viewer', as: 'embeddable_iiif_viewer'

  resources :bookmarks do
    concerns :exportable
    collection do
      delete 'clear'
    end
  end

  namespace :teach do
    get 'using-materials'
  end

  namespace :participate do
    get 'contribute'
    get 'nominate'
    get 'harmful_content'
    get 'partner-services'
    post 'nomination'
  end

  namespace :about do
    get 'mission'
    get 'policy'
    get 'partners-sponsors'
    get 'api'
    get 'harmful-content'
    get 'harmful-content-form'
    post 'harmful_content_submit'
  end

  namespace :help do
    get 'search'
    get 'refine-items'
    get 'refine-collections'
    get 'map'
  end

  get '/contact(/:formtype)', to: 'contact#index', formtype: /|dlg|crdl|ghnp/, as: 'contact'

  get '/id::record_id', to: redirect('/record/%{record_id}'), status: 301

  get '/*do_tag', do_tag: /do(?:-[a-z0-9-]+)?:[a-z0-9,_-]+/, to: redirect { |path_params, _req|
    if (m=path_params[:do_tag].match /^do(?<alt>-[a-z0-9-]+)?:(?<record_id>[a-z0-9,_-]+)$/)
      "https://dlg.galileo.usg.edu/do#{m[:alt]}:#{m[:record_id]}"
    end
  }

  root to: 'homepage#index'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/meta_api_v2.rb
# frozen_string_literal: true

# Class to wrap Meta API V2
class MetaApiV2
  include HTTParty
  base_uri Rails.application.credentials.meta_api_url.dig(Rails.env.to_sym)

  DEFAULT_QUERY_PARAMS = { portal: 'georgia' }.freeze

  def initialize
    @options = {
      headers: { 'X-User-Token': Rails.application.credentials.meta_api_key }
    }
  end

  def features(query = {})
    get_many '/features', params(query)
  end

  def holding_institutions(query = {})
    get_many '/holding_institutions', params(query)
  end

  def holding_institution(id)
    get "/holding_institutions/#{id}"
  end

  def collections(query = {})
    get_many '/collections', params(query)
  end

  def collection(id)
    get "/collections/#{id}"
  end

  def collection_resource(collection_id, resource_slug)
    get "/collections/#{collection_id}/resource/#{resource_slug}"
  end

  private

  def get(url, options = params)
    data = self.class.get(url, options).parsed_response
    data.present? ? OpenStruct.new(data) : nil
  rescue StandardError => e
    # TODO: is this right? test this case
    OpenStruct.new
  end

  def get_many(url, options = params)
    response = self.class.get(url, options).parsed_response
    if response.present?
      response.map do |entity|
        OpenStruct.new entity
      end
    else
      nil
    end
  rescue StandardError => e
    []
  end

  def params(query = {})
    options = @options
    options[:query] = query.merge(DEFAULT_QUERY_PARAMS)
                           .reject { |_, v| v.blank? }
    options
  end
end

app/helpers/records_helper.rb
# frozen_string_literal: true

# helper methods for RecordsController views
module RecordsHelper
  def set_page_title
    prefix = if @collection && !has_search_parameters?
               "#{@collection.display_title} Collection Items"
             elsif @collection && has_search_parameters?
               "#{render_search_to_page_title(params)} - #{@collection.display_title} Collection Items"
             end
    @page_title = "#{prefix} - #{application_name}"
  end

  def collection_limited_results?
    @collection && @response.documents
  end

  def serial_limited_results?
    @serial && @response.documents
  end

  def multivalued_collection_field(field, connector = ', ', linkify: false)
    return '' unless field&.any?

    field = field.map { |value| find_urls_and_linkify(value)} if linkify

    field.map.to_a.to_sentence(two_words_connector: connector).html_safe
  end

  def collection_field_links(field_values, facet)
    return [] unless field_values&.any?

    links = field_values.map do |val|
      link_to(val, search_action_path(search_state.add_facet_params_and_redirect(facet, val)))
    end
    links.to_sentence.html_safe
  end

  def rights_statement_icons(dc_right)
    return '' unless dc_right&.any?

    image_tags = []
    I18n.t([:rights])[0].each do |r|
      dc_right.each do |rights|
        next unless r[1][:uri] == rights

        image_tags << rights_statement_icon_link(r)
      end
    end
    image_tags.join('').html_safe
  end

  def more_about_field_tag(label, field_value)
    tag.p(tag.strong(label) + tag.br + field_value, class: label.parameterize.underscore) if field_value.present?
  end

  def name_letter_pressed?(letter, params)
    # Letter should never be pressed when query is present
    params['q'].blank? && (
      (params[:first_char].blank? && letter == @a_to_z.without('0-9').first) ||
        params[:first_char]&.upcase == letter
    )
  end

  def formatted_manifest_url(document)
    return document.iiif_manifest_url unless document.iiif_ids&.any?

    path = URI(document.iiif_manifest_url).path
    if Rails.env.development?
      URI::HTTP.build(host: request.host, port: request.port, path: path).to_s
    else
      URI::HTTPS.build(host: request.host, path: path).to_s
    end
  end

  def json_hash_field(field)
    return '' unless field

    tags = field.map do |identifier|
      content_tag(:span, identifier['type'], class: 'badge badge-primary') + ' ' + identifier['value']
    end

    tags.map.to_a.to_sentence.html_safe
  end
end

app/views/records/_collection_details.html.erb
<div class="collection-details">
  <h2 class="collections-heading"><%= @collection.title %></h2>
  <%= render('institution_icons', institutions: @institutions) if @institutions %>
  <p><%= find_urls_and_linkify @collection.short_description %></p>
  <%= more_about_field_tag('Sensitive Content', multivalued_collection_field(@collection.sensitive_content)) %>
  <div class="panel-group text-center" id="accordion">
    <%= render 'collection_more_about_card' %>
    <% if @collection.collection_resources.any? %>
      <%= render 'collection_resources_card' %>
    <% end %>
  </div>
  <% if @collection.sponsor_note.present? %>
    <div class="row">
      <div class="col-md-12">
        <%= render 'collection_sponsor' %>
      </div>
    </div>
  <% end %>
</div>

app/views/records/_collection_more_about_card.html.erb
<div class="row mb-2">
  <div class="col">
    <div class="card">
      <a data-toggle="collapse" data-parent="#accordion" href="#collapse1" class="collapsed" aria-expanded="false">
        <div class="card-header">
          <h3 class="panel-title">
            More About This Collection <i class="fa fa-caret-down" aria-hidden="true"></i>
          </h3>
        </div>
      </a>
      <div id="collapse1" class="collapse" aria-expanded="false" style="height: 0px;">
        <div class="card-body text-left">
          <%= more_about_field_tag(t('search.labels.dcterms_creator'), collection_field_links(@collection.dcterms_creator, 'creator_facet')) %>
          <%= more_about_field_tag(t('search.labels.dcterms_contributor'), multivalued_collection_field(@collection.dcterms_contributor)) %>
          <%= more_about_field_tag(t('search.labels.dcterms_publisher'), multivalued_collection_field(@collection.dcterms_publisher)) %>
          <%= more_about_field_tag(t('search.labels.dc_date'), multivalued_collection_field(@collection.dc_date)) %>
          <%= more_about_field_tag(t('search.labels.dcterms_subject'), collection_field_links(@collection.dcterms_subject, 'subject_facet')) %>
          <%= more_about_field_tag(t('search.labels.dlg_subject_personal'), collection_field_links(@collection.dlg_subject_personal, 'subject_personal_facet')) %>
          <%= more_about_field_tag(t('search.labels.dcterms_spatial'), collection_field_links(@collection.dcterms_spatial, 'location_facet')) %>
          <%= more_about_field_tag(t('search.labels.dcterms_medium'), collection_field_links(@collection.dcterms_medium, 'medium_facet')) %>
          <%= more_about_field_tag(t('search.labels.dcterms_type'), multivalued_collection_field(type_labels_for_show_page @collection.dcterms_type)) %>
          <%= more_about_field_tag(t('search.labels.dcterms_format'), multivalued_collection_field(@collection.dcterms_format)) %>
          <%= more_about_field_tag(t('search.labels.dcterms_description'), multivalued_collection_field(@collection.dcterms_description, linkify: true)) %>
          <%= more_about_field_tag(t('search.labels.edm_is_shown_at'), linkify(value: [@collection.md_url])) %>
          <%= more_about_field_tag(t('search.labels.dcterms_language'), multivalued_collection_field(@collection.dcterms_language)) %>
          <%= more_about_field_tag(t('search.labels.dcterms_rights_holder'), multivalued_collection_field(@collection.dcterms_rights_holder)) %>
          <%= more_about_field_tag(t('search.labels.dcterms_is_part_of'), multivalued_collection_field(@collection.dcterms_is_part_of)) %>
          <%= more_about_field_tag(t('search.labels.dcterms_provenance'), collection_field_links(@collection.dcterms_provenance, 'provenance_facet')) %>
          <%= more_about_field_tag(t('search.labels.dc_right'), rights_statement_icons(@collection.dc_right) ) %>
          <%= more_about_field_tag(t('search.labels.sensitive_content'), multivalued_collection_field(@collection.sensitive_content)) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/records/_collection_resources_card.html.erb
<div class="row mb-2">
  <div class="col">
    <div class="card">
      <a data-toggle="collapse" data-parent="#accordion" href="#collapse2" class="collapsed" aria-expanded="false">
        <div class="card-header">
          <h3 class="panel-title">
            Additional Resources <i class="fa fa-caret-down" aria-hidden="true"></i>
          </h3>
        </div>
      </a>
      <div id="collapse2" class="collapse" aria-expanded="false" style="height: 0px;">
        <div class="card-body text-left">
          <ul>
            <% @collection.collection_resources.each do |resource| %>
              <li>
                <%= link_to resource['title'], resource['use_external_link'] ?
                                                 resource['external_link'] :
                                                 collection_resource_collections_path(@collection.id, resource['slug'])%>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/records/_collection_resources_panel.html.erb
<div class="col-md-12 col-lg-6">
  <div class="panel panel-default resources-panel">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse2" class="collapsed" aria-expanded="false">
          Additional Resources <span class="caret"></span></a>
      </h4>
    </div>
    <div id="collapse2" class="panel-collapse collapse" aria-expanded="false">
      <div class="panel-body text-left">
        <ul>
          <% @collection.collection_resources.each do |resource| %>
            <li>
              <% if resource['use_external_link'] %>
                <%= link_to resource['title'], resource['external_link'] %>
              <% else %>
                <%= link_to resource['title'], collection_resource_path(
                  @collection.record_id,
                  resource['slug']
                ) %>
              <% end %>

            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/records/_collection_sponsor.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="alert alert-secondary sponsor-info">
      <div class="row">
        <div class="col-md-3 col-sm-12">
          <%= image_tag server_image_url(@collection.sponsor_image), class: 'img-fluid sponsor-image', alt: 'Sponsor Image' %>
        </div>
        <div class="col-md-9 col-sm-12">
          <p>
            <%= @collection.sponsor_note.html_safe %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/records/_collection_sponsor_panel.html.erb
<div class="bs-callout bs-callout-info sponsor-info">
  <div class="col-lg-3 col-md-12">
    <%= image_tag cache_server_image_link(@collection.sponsor_image['url']), class: 'img-responsive sponsor-image', alt: 'Sponsor Image' %>
  </div>
  <div class="col-lg-9 col-md-12">
    <p>
      <%= @collection.sponsor_note.html_safe %>
    </p>
  </div>
</div>

app/views/records/_fulltext_download.html.erb
<% if @document.fulltext %>
  <%= link_to t('show.tools.download_text'), solr_document_fulltext_path(@document.id, format: :text) %>
<% end %>

app/views/records/_institution_icons.html.erb
<div class="row ">
  <div class="col-sm-12">
    <div class="holding-institution-logos text-center">
      <% if @institutions.any? %>
        <% @institutions.each do |inst| %>
          <img class="holding-institution-logo" src="<%= server_image_url(inst.image) %>" alt="<% inst.title %>">
        <% end %>
      <% else %>
        <img class="holding-institution-logo" src="<%= server_image_url(@collection.holding_institution_image) %>" alt="<% @collection.title %>">
      <% end %>
    </div>
  </div>
</div>

app/views/records/_reuse.html.erb
<%= link_to t('show.tools.reuse'), teach_using_materials_path %>

app/views/records/_serial_details.html.erb
<div class="serial-details">
  <h2 class="serial-heading"><%= @serial.title %></h2>
  <div class="panel-group text-center" id="accordion">
    <%= render 'serial_more_about_card' %>
  </div>
</div>

app/views/records/_serial_more_about_card.html.erb
<div class="row mb-2">
  <div class="col">
    <div class="card">
      <a data-toggle="collapse" data-parent="#accordion" href="#collapse1" class="collapsed" aria-expanded="false">
        <div class="card-header">
          <h3 class="panel-title">
            More About This Serial <i class="fa fa-caret-down" aria-hidden="true"></i>
          </h3>
        </div>
      </a>
      <div id="collapse1" class="collapse" aria-expanded="false" style="height: 0px;">
        <div class="card-body text-left">
          <%= more_about_field_tag(t('search.labels.dcterms_creator'), collection_field_links(@serial.dcterms_creator, 'creator_facet')) %>
          <%= more_about_field_tag(t('search.labels.dcterms_publisher'), multivalued_collection_field(@serial.dcterms_publisher)) %>
          <%= more_about_field_tag(t('search.labels.dcterms_frequency'), multivalued_collection_field(@serial.dcterms_frequency_display)) %>
          <%= more_about_field_tag(t('search.labels.dc_date'), multivalued_collection_field(@serial.dc_date)) %>
          <%= more_about_field_tag(t('search.labels.dcterms_subject'), collection_field_links(@serial.dcterms_subject, 'subject_facet')) %>
          <%= more_about_field_tag(t('search.labels.dcterms_subject_fast'), multivalued_collection_field(@serial.dcterms_subject_fast)) %>
          <%= more_about_field_tag(t('search.labels.dlg_subject_personal'), collection_field_links(@serial.dlg_subject_personal, 'subject_personal_facet')) %>
          <%= more_about_field_tag(t('search.labels.dcterms_spatial'), collection_field_links(@serial.dcterms_spatial, 'location_facet')) %>
          <%= more_about_field_tag(t('search.labels.dcterms_medium'), collection_field_links(@serial.dcterms_medium, 'medium_facet')) %>
          <%= more_about_field_tag(t('search.labels.dcterms_description'), multivalued_collection_field(@serial.dcterms_description)) %>
          <%= more_about_field_tag(t('search.labels.dcterms_language'), multivalued_collection_field(@serial.dcterms_language)) %>
          <%= more_about_field_tag(t('search.labels.dcterms_replaces'),
                                   multivalued_collection_field(@serial.dcterms_replaces
                                                                  &.zip(@serial.preceding_slugs)
                                                                  &.map {|ti, slug| link_to ti, serial_home_path(slug)})
              ) %>
          <%= more_about_field_tag(t('search.labels.dcterms_is_replaced_by'),
                                   multivalued_collection_field(@serial.dcterms_is_replaced_by
                                                                  &.zip(@serial.succeeding_slugs)
                                                                  &.map {|ti, slug| link_to ti, serial_home_path(slug)})
              ) %>
          <%= more_about_field_tag(t('search.labels.external_identifiers'), json_hash_field(@serial.external_identifiers)) %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/records/fulltext.text.erb
<%= @document.fulltext %>

app/views/records/index.html.erb
<section id="record-results">
  <h1><%= t('menu.explore_sub.items') %></h1>
  <div class="row">
    <div id="sidebar" class="<%= sidebar_classes %>">
      <%= render 'search_sidebar' %>
    </div>
    <div id="content" class="<%= main_content_classes %> ">
      <%= render 'collection_details' if collection_limited_results? %>
      <%= render 'serial_details' if serial_limited_results? %>
      <%= render 'search_results' %>
    </div>
  </div>
</section>