config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new

  resources :solr_document, only: [:show], path: '/record', controller: 'records' do
    concerns :exportable
    get 'fulltext', to: 'records#fulltext'
    get 'presentation/manifest', to: 'records#presentation_manifest'
    get 'harmful_content', to: 'records#harmful_content'
  end

  resource :records, only: %i[index show] do
    get 'map', to: 'map', as: 'map'
    concerns :searchable
    concerns :range_searchable
    collection do
      get 'suggest/:facet_name', to: 'records#suggest', as: 'suggest_facet', defaults: { format: 'json' }
    end
  end

  # so related routes are available with the *_catalog_url that BL expects in addition to *_record_url
  resource :records, only:[], as: :catalog do
    concerns :searchable
  end

  get '/collection/:collection_record_id', to: 'records#index', as: 'collection_home'

  if FeatureFlags.enabled? :serials
    get '/serial/:serial_record_id', to: 'records#index', as: 'serial_home'
  else
    get '/serial/:serial_record_id', to: redirect {|path_params, _request|
      TemporaryRedirectService.legacy_route_for_serial(path_params[:serial_record_id])
    }
  end
  get '/serials/:serial_record_id', to: redirect('/serial/%{serial_record_id}')

  resource :collections, only: [:index] do
    get 'map', to: 'map', as: 'map'
    concerns :searchable
    concerns :range_searchable
    member do
      get(
        '/:collection_record_id/:collection_resource_slug',
        to: 'collection_resources#show',
        as: 'collection_resource'
      )
    end
  end

  resource :serials, only: %i[index] do
    concerns :searchable
    concerns :range_searchable
  end

  get '/collections/:collection_slug', to: 'records#index'

  resource :institutions, only: %i[index], path: '/institutions(/:first_char)', first_char: /[a-zA-Z]|0-9/, controller: 'institutions' do
    concerns :searchable
  end

  resources :institution_solr_documents, only: [:show], path: '/institutions/', controller: 'institutions' do
    concerns :exportable
  end

  resources :collection_solr_documents, only: [:show], path: '/collections/', controller: 'collections' do
    concerns :exportable
  end

  resources :serial_solr_documents, only: [:show], path: '/serials/', controller: 'serials' do
    concerns :exportable
  end

  get '/search', to: 'advanced#index', as: 'search'
  get '/counties', to: 'counties#index', as: 'counties'

  get '/iiif-viewer', to: 'iiif_viewer#iiif_viewer', as: 'iiif_viewer'
  get '/iiif-embeddable', to: 'iiif_viewer#embeddable_iiif_viewer', as: 'embeddable_iiif_viewer'

  resources :bookmarks do
    concerns :exportable
    collection do
      delete 'clear'
    end
  end

  namespace :teach do
    get 'using-materials'
  end

  namespace :participate do
    get 'contribute'
    get 'nominate'
    get 'harmful_content'
    get 'partner-services'
    post 'nomination'
  end

  namespace :about do
    get 'mission'
    get 'policy'
    get 'partners-sponsors'
    get 'api'
    get 'harmful-content'
    get 'harmful-content-form'
    post 'harmful_content_submit'
  end

  namespace :help do
    get 'search'
    get 'refine-items'
    get 'refine-collections'
    get 'map'
  end

  get '/contact(/:formtype)', to: 'contact#index', formtype: /|dlg|crdl|ghnp/, as: 'contact'

  get '/id::record_id', to: redirect('/record/%{record_id}'), status: 301

  get '/*do_tag', do_tag: /do(?:-[a-z0-9-]+)?:[a-z0-9,_-]+/, to: redirect { |path_params, _req|
    if (m=path_params[:do_tag].match /^do(?<alt>-[a-z0-9-]+)?:(?<record_id>[a-z0-9,_-]+)$/)
      "https://dlg.galileo.usg.edu/do#{m[:alt]}:#{m[:record_id]}"
    end
  }

  root to: 'homepage#index'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/controllers/about_controller.rb
# frozen_string_literal: true

# "About" menu items static content controller
class AboutController < HomepageController
  def mission; end

  def policy; end

  def partners_sponsors; end

  def api; end

  def harmful_content; end

  def harmful_content_form; end

  def harmful_content_submit
    mail = HarmfulContentMailer.harmful_content_submission harmful_content_params
    sent = if mail.respond_to? :deliver_now
             mail.deliver_now
           else
             mail.deliver
           end
    respond_to do |format|
      format.html do
        if sent
          flash[:notice] = I18n.t('mail.harmful_content.status.sent')
        else
          flash[:error] = I18n.t('mail.harmful_content.status.failed')
        end
        redirect_to about_harmful_content_path
      end
    end
  end

  def harmful_content_params
    params.permit(:item_url, :concern, :note, :name, :email)
  end
end

app/views/about/api.html.erb
<section id="about">
  <div class="container-xl">
    <h1>DLG API</h1>
    <p>This site provides an API for researchers and digital humanists. Responses come in either XML or JSON flavor.</p>
    <h2>Endpoints</h2>
    <table class="table">
      <tr>
        <th>URL Scheme</th>
        <th>Description</th>
        <th>Expected Response</th>
        <th>Notes</th>
        <th>Example</th>
      </tr>
      <tr>
        <td>
          <code>https://dlg.usg.edu/records.json</code><br>
          <code>https://dlg.usg.edu/records.xml</code>
        </td>
        <td>
          Returns all search records in a paginated list with facet data.
        </td>
        <td>
          Item(s), Facet information
        </td>
        <td>
          Combine with query parameters to limit results. Results are paginated.
        </td>
        <td>
          <a href="https://dlg.usg.edu/records.json?f%5Bcounties_facet%5D%5B%5D=Clarke&only_path=true&op=ANDq=columns&search_field=all_fields&sort=score+desc%2C+year+asc">JSON Results for 'columns' in Clarke County</a>
        </td>
      </tr>
      <tr>
        <td>
          <code>https://dlg.usg.edu/record/{<var>identifier</var>}.json</code><br>
          <code>https://dlg.usg.edu/record/{<var>identifier</var>}.xml</code>
        </td>
        <td>
          Returns all available metadata for record corresponding to <var>identifier</var>.
        </td>
        <td>
          Item
        </td>
        <td>
          &nbsp;
        </td>
        <td>
          <a href="https://dlg.usg.edu/record/dlg_larc_jlc0378.json">JSON for <var>dlg_larc_jlc0378</var></a>
        </td>
      </tr>
      <tr>
        <td>
          <code>https://dlg.usg.edu/records.json?search_field=record_id&q={identifier}+OR+{another_identifier}</code>
        </td>
        <td>
          Returns JSON for a specific set of records using record IDs separated by OR
        </td>
        <td>
          Item(s), Facet information
        </td>
        <td>
          Identifiers can be extracted from individual record page URLs (in <a href="https://dlg.usg.edu/record/gsu_lane_13327">this example</a> the ID is <var>gsu_lane_13327</var>)
        </td>
        <td>
          <a href="https://dlg.usg.edu/records.json?search_field=record_id&q=dlg_vsbg_jaj111+OR+dlg_vsbg_jaj053">JSON for <var>dlg_vsbg_jaj111</var> and <var>dlg_vsbg_jaj053</var></a>
        </td>
      </tr>
      <tr>
        <td>
          <code>https://dlg.usg.edu/collections.json</code><br>
          <code>https://dlg.usg.edu/collections.xml</code>
        </td>
        <td>
          Returns all collection search records in a paginated list with facet data.
        </td>
        <td>
          Collection(s), Facet information
        </td>
        <td>
          Combine with query parameters to limit results. Results are paginated.
        </td>
        <td>
          <a href="https://dlg.usg.edu/collections.json?only_path=true&op=ANDq=architecture&search_field=all_fields&sort=score+desc%2C+year+asc">JSON Results for Collections matching 'architecture'</a>
        </td>
      </tr>
      <tr>
        <td>
          <code>https://dlg.usg.edu/collection/{<var>identifier</var>}.json</code><br>
          <code>https://dlg.usg.edu/collection/{<var>identifier</var>}.xml</code>
        </td>
        <td>
          Returns all items contained in the Collection corresponding to <var>identifier</var>.
        </td>
        <td>
          Item(s), facet information
        </td>
        <td>
          &nbsp;
        </td>
        <td>
          <a href="https://dlg.usg.edu/collection/dlg_gacoch.json">JSON for records in <var>dlg_gacoch</var></a>
        </td>
      </tr>
    </table>
  </div>
</section>

app/views/about/harmful_content.html.erb
<section id="about">
  <div class="container-xl">
    <h1>Digital Library of Georgia Statement on Potentially Harmful Content</h1>
    <p>The Digital Library of Georgia (DLG) shares materials from libraries, museums, and others in Georgia and the U.S.  online. Our websites include historical and primary sources from many cultures and time periods. Some content (or its descriptions) may be harmful and difficult to view. These materials may be graphic or reflect biases.  In some cases, they may conflict with strongly held cultural values, beliefs or restrictions.</p>
    <p>We provide access to these materials to preserve the historical record, but we do not endorse the attitudes, prejudices, or behaviors found within them.</p>
    <p>Please approach the materials found on these sites with respect for the cultures and people they document.</p>

    <h2>Creation of the Statement</h2>
    <p>The DLG is a member service hub of the Digital Public Library of America (DPLA). The DLG modeled its statement on DPLA’s. DPLA staff and its metadata working group drafted the DPLA statement. Outside experts and the network reviewed it before approval.</p>
    <p>DLG staff simplified the statement’s language to improve its readability based on Georgia Department of Education eighth grade reading levels. Staff at GALILEO, Georgia Public Library Service, NGE, UGA Libraries, and DLG partners reviewed the draft statement.</p>
    <h2>Frequently Asked Questions</h2>
    <h3>Where does this content come from?</h3>
    <p>The DLG partners with cultural heritage organizations across Georgia and the U.S. Together, we digitize and share historical content online for free. Each contributor shares materials with the DLG according to its specific policies and goals. We also create exhibits and primary source sets that feature our partners’ content.</p>
    <h3>What harmful or difficult content may be found in the DLG websites?</h3><br>
      Some items may:
    <ul>
      <li>Reflect white supremacist and imperialist views, including racist, sexist, and xenophobic opinions and attitudes.</li>
      <li>Be biased against or exclude diverse views on sexuality, gender, ableism, religion, and more.</li>
      <li>Include graphic content such as violent death, medical procedures, crime, wars, natural disasters and more.</li>
      <li>Demonstrate bias and exclusion in library/museum collecting and digitization.</li>
      <li>Depict traditional knowledge and offend against strongly held cultural prohibitions.</li>
    </ul>
    <h3>Why does DLG make this content available?</h3>
    <p>The DLG and its partners collect, preserve, and present these materials as part of the historic record. Together, they work to balance the preservation of history with its sensitive display.</p>
    <h3>How is this material described? Why are some of the terms used harmful?</h3>
    <ul>
      <li>Librarians and archivists choose what language to use when describing materials. Some descriptions were written in the past and use language that was accepted at the time.</li>
      <li>Librarians and archivists often re-use language provided by creators or former owners of the material. This can provide important context, but can also reflect biases and prejudices.</li>
      <li>Librarians and archivists often use standardized sets of terms to describe materials.  Some of these terms are outdated, offensive, or insensitive.</li>
      <li>Communities with less privilege have had less control over how they are portrayed and described.</li>
      <li>Librarians and archivists sometimes make mistakes or use poor judgment.</li>
    </ul>
    <p>The DLG pledges to help its partners assess and update harmful descriptions.</p>
    <h3>How are the DLG and its partners addressing this issue?</h3>
    We are:
    <ul>
      <li>Including warnings on collections with this type of content.</li>
      <li>Prioritizing digitization of content from less privileged communities.</li>
      <li>Working directly with misrepresented communities when describing them.</li>
      <li>Revising and enhancing descriptions with more respectful, community-selected terms.</li>
      <li>Creating new, more inclusive standardized terms.</li>
      <li>Listening to users,  researching  to find solutions,  and sharing our results.</li>
      <li>Evaluating current policies for practices that prioritize one culture and/or group over another.</li>
      <li>Training our contributors in inclusive partnerships, digitization, and description.</li>
    </ul>

    <h3>What happens if I report harmful content?</h3>
    <p>
      We encourage our users to <%= link_to 'report harmful content', about_harmful_content_form_path %>. The DLG will
      forward your report to the owning institution.  They will determine whether to change or remove the content.
      Institutions weigh potential harm, accurate preservation of the historical record, professional practices, and
      limited resources. The DLG will use all reports to better understand the issue and educate others.
    </p>
  </div>
</section>

app/views/about/harmful_content_form.html.erb
<%= render partial: 'shared/flash_msg', layout: 'shared/flash_messages' %>
<section id="participate">
  <div class="container-xl">
    <h1>Report Harmful Content</h1>
    <p>
      Our websites include historical and primary sources from many cultures and time periods. Some content (or its
      descriptions) may be harmful and difficult to view. These materials may be graphic or reflect biases. In some
      cases, they may conflict with strongly held cultural values, beliefs or restrictions. We provide access to these
      materials to preserve the historical record, but we do not endorse the attitudes, prejudices, or behaviors found
      within them.
    </p>
    <p>
      We encourage reports of harmful content. The DLG will forward your report to the owning institution. They will
      determine whether to change or remove the content. Institutions weigh potential harm, accurate preservation of
      the historical record, professional practices, and limited resources. The DLG will use all reports to better
      understand the issue and educate others.
    </p>
    <p>
      For more information on potentially harmful content, please read our <%= link_to 'statement', about_harmful_content_path %>.
    </p>
    <br>
    <%= form_with url: about_harmful_content_submit_path, method: :post do |f| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">Description</h2>
      </div>
      <div class="panel-body">
        <div class="form-group">
          <%= f.label :item_url, t('mail.harmful_content.questions.item_url') %>
          <%= f.text_field :item_url, class: 'form-control', value: (solr_document_url(@document) if @document) %>
        </div>
        <div class="form-group">
          <%= f.label :concern, t('mail.harmful_content.questions.concern') %>
          <%= f.text_area :concern, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :note, t('mail.harmful_content.questions.note') %>
          <%= f.text_area :note, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">Your contact information (if you would like us to reach out - this is optional)</h2>
      </div>
      <div class="panel-body">
        <div class="form-group">
          <%= f.label :name, t('mail.harmful_content.questions.name') %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email, t('mail.harmful_content.questions.email') %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
      </div>
    </div>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
</section>

app/views/about/partners_sponsors.html.erb
<section id="about">
  <div class="container-xl">
    <h1>DLG Partners and Sponsors</h1>
    <h2>Project Sponsors</h2>
    <p>
      The following organizations have provided financial support to the Digital
      Library of Georgia and GALILEO for conversion projects:
    </p>
    <ul>
      <li><a href="https://www.galileo.usg.edu">GALILEO, Georgia's Virtual Library, an initiative of the University System of Georgia</a></li>
      <li><a href="http://www.georgialibraries.org">Georgia Public Library Service (Board of Regents, University System of Georgia)</a></li>
      <li><a href="http://gaarts.org/">Georgia Council for the Arts</a></li>
      <li><a href="http://www.georgiahumanities.org">Georgia Humanities Council</a></li>
      <li><a href="https://www.libs.uga.edu">University of Georgia Libraries</a></li>
      <li><a href="https://www.clir.org/">The Council on Library and Information Resources</a></li>
      <li><a href="https://dp.la">Digital Public Library of America</a></li>
      <li><a href="http://www.imls.gov">Institute for Museum and Library Services</a></li>
      <li><a href="https://knightfoundation.org/">Knight Foundation</a></li>
      <li><a href="http://www.neh.gov">National Endowment for the Humanities</a></li>
      <li><a href="http://www.archives.gov/nhprc/">National Historical Publications and Records Commission</a></li>
      <li>Alice L. Gilbert Foundation</li>
      <li>Burke County Genealogical and Historical Society</li>
      <li>Chattooga County Historical Society</li>
      <li>Douglas County Georgia Genealogy Society</li>
      <li>Estate of Alice L. Gilbert</li>
      <li>Flint Energies Foundation</li>
      <li>Flint River Regional Library System</li>
      <li>Forsyth County Public Library</li>
      <li>Frances Wood Wilson Foundation, Inc.</li>
      <li>Friends of the Augusta Library</li>
      <li>Friends of the Houston County Public Library</li>
      <li>Georgia Historical Records Advisory Council</li>
      <li>Gwinnett Historical Society</li>
      <li>Houston County Public Library System</li>
      <li>Ingram Library, University of West Georgia</li>
      <li>Knox Foundation</li>
      <li>Lucy Hilton Maddox Memorial Library</li>
      <li>Main Street News</li>
      <li>Mercer University Libraries</li>
      <li>Middle Georgia State University Library</li>
      <li>Monroe County Historical Society</li>
      <li>Newton County Library System</li>
      <li>R.J. Taylor Foundation</li>
      <li>Roman Catholic Archdiocese of Atlanta</li>
      <li>Roman Catholic Diocese of Savannah</li>
      <li>Spalding County SPLOST</li>
      <li>Srochi family of Atlanta</li>
      <li>Taylor County Historical-Genealogical Society</li>
      <li>Tillotson-Menlo Charitable Foundation</li>
      <li>Watson-Brown Foundation</li>
    </ul>

    <h2>DLG Partners</h2>
    <p>
      For a current list of DLG content partners, please see our <%= link_to 'institutions page', search_institutions_path %>
    </p>
  </div>
</section>

app/views/about/policy.html.erb
<section id="about">
  <div class="container-xl">
    <h1>Collection Development Policy</h1>
    <h2>Digitized Collections</h2>
    <p>The Digital Library of Georgia, working together with Georgia's libraries, archives, museums, and other institutions of cultural heritage, provides access to the cultural and historical resources of the state of Georgia through ongoing development, maintenance, and preservation of online digital collections and resources. Original formats included may be text-based, including manuscripts, letters, diaries, and published works such as books and pamphlets, photographs, maps, art, artifacts, audio and video, graphic materials including architectural plans and drawings, and microfilm.</p>
    <p>The Audience of the Digital Library of Georgia consists of five segments:</p>
    <ul>
      <li>Casual User - <span class="italicized">Similar to a museum visitor viewing an exhibit, or the library patron browsing the stacks, seeking general information, or recreational reading or viewing materials. Casual users are usually interested in browsing for information.</span></li>
      <li>Student/K-12/Lifelong Learner - <span class="italicized">This group is usually seeking information for a specific purpose to support their learning goals, advance their career, or for general enlightenment. This group includes undergraduate and graduate college and university students and students in grades K-12, as well as teachers and instructors who may be using digitized resources in the classroom.</span></li>
      <li>Information Seeker/Hobbyist - <span class="italicized">The hobbyist or information seeker desires more in-depth information on a particular topic. This group includes genealogists, amateur historians, and others who desire information on a narrowly defined topic or set of topics. This class of users is interested in searching for specific information.</span></li>
      <li>Scholar/Researcher - <span class="italicized">The scholar or researcher desires in-depth information to support scholarship and research in support of scholarly publication.</span></li>
      <li>Government/Business Community - <span class="italicized">The government or business community is interested in obtaining information to support government activities or business initiatives.</span></li>
    </ul>
    <p>Collections, materials, or items may be nominated for digitization by any interested party using the <%= link_to 'Digital Library of Georgia Digitization Nomination Form', participate_nominate_path %>.</p>
    <p>Collections nominated for digitization and/or inclusion in the Digital Library of Georgia will be judged based on the following criteria.</p>
    <ul>
      <li><strong>Mission.</strong> Proposed materials or collections must conform to the mission of the Digital Library of Georgia and be related to the culture and history of the state of Georgia.</li>
      <li><strong>Restrictions.</strong> Materials that are restricted by the donor or other owner will not be digitized unless permission can be obtained.</li>
      <li><strong>Copyright.</strong> Materials that are clearly in the public domain will be given priority for digitization. Where public domain status is questionable, a decision will be made on a case by case basis. When materials are under copyright restrictions, they will not be digitized unless permission is obtained or a compelling orphan works case may be made.</li>
      <li><strong>Documentation/Description.</strong> Materials or collections that are completely or partially described, captioned, labeled, processed, or cataloged will be given priority for digitization. Other instances will be handled on a case by case basis depending on factors such as the type and depth of description required, need for research, etc.</li>
      <li><strong>Accessibility.</strong> Materials that are hard to access due to preservation concerns or are only available to a limited audience due to security restrictions will be given priority for digitization.</li>
      <li><strong>Use.</strong> Materials that are heavily used by researchers, other patrons, or staff will be given greater priority for digitization.</li>
      <li><strong>Diversity.</strong> Materials that represent the cultural, political, social, geographic, and/or economic diversity of the state of Georgia will be given priority.</li>
      <li><strong>Value.</strong> Materials that have high research, artifactual, or evidential value and/or are of particular interest to a key audience will have high priority for digitization.</li>
      <li><strong>Potential for Added Value.</strong> Materials for which access will be substantially improved by digitization and which have a high potential for added value in the digital environment will be given priority. Examples of added value that the materials may lend themselves to include:
        <ul>
          <li>Creation and/or addition of supplemental resources to allow users 	to better understand, navigate, and use the collection</li>
          <li>Linkages between materials</li>
          <li>Virtual collections of materials based around a creator, topic, subject, or similar theme</li>
          <li>New metadata, description, and finding aids in electronic form</li>
          <li>The ability to search through the creation of electronic text</li>
          <li>New ways to use or analyze the originals</li>
        </ul>
      </li>
      <li><strong>Duplication of Effort.</strong> Materials that are publicly available in digital form elsewhere at a level of quality that meets the needs of the audience of the Digital Library of Georgia will not be digitized. Note that the DLG Georgia Portal may link to items related to the mission of the Digital Library of Georgia.</li>
      <li><strong>Cooperative Potential.</strong> If the materials have the potential to be related to others held by different repositories or organizations, including materials already digitized or being considered for digitization, the priority for digitization is higher if it is likely that a cooperative or multi-collection digitization initiative may result.</li>
      <li><strong>Availability of Local or Additional Resources.</strong> Following on cooperative potential, if a repository or other organization can provide support in the form of staff time, equipment, or funding - especially at a local basis - to digitize materials to the standards required by the Digital Library of Georgia those collections may be given greater priority to take advantage of these opportunities.</li>
      <li><strong>Technology.</strong> Materials for which appropriate technology, processes, and best practices already exist for digitization will generally have priority. Projects that explore or require implementation of new technologies will be considered depending on the availability of resources and funding.</li>
    </ul>
    <h2>DLG Georgia Portal</h2>
    <p>The DLG Georgia Portal links historical and cultural collections digitized by the DLG and held locally in GALILEO with digital collections, materials, sites, items or similar resources held by cultural and/or other non-profit organizations throughout the state and elsewhere by means of metadata aggregation.</p>
    <p>The DLG Portal Service will record metadata about and link to sites meeting the following criteria:</p>
    <ul>
      <li>Provides digitized resources for collections representing Georgia's history and culture</li>
      <li>Makes the resource available at no cost</li>
      <li>Has a plan for ongoing sustainability and maintenance</li>
      <li>Respects copyright by ensuring that materials are in the public domain or cleared for public distribution</li>
      <li>Priority will be given to sites containing cultural materials digitized in accordance with standard best practices for digital imaging recommended by the Digital Library of Georgia</li>
    </ul>
    <h3>Ownership</h3>
    <p>The Digital Library of Georgia does not claim ownership of digital objects linked to from the DLG Georgia Portal. Ownership remains with the originating site. Note that collections digitized and mounted by the Digital Library of Georgia and GALILEO are linked to from the DLG Georgia Portal in the same way as other participating sites. All metadata created by the Digital Library of Georgia and included in the portal is licensed under a Creative Commons CC0 license, and users may reuse and share freely.</p>
    <h3>Accuracy</h3>
    <p>Responsibility for accuracy of data, facts, and information presented rests with the institution providing the digital resource. The Digital Library of Georgia does not warrant any information on the sites linked to by the portal. The Digital Library of Georgia recommends that all sites have a means of collection information regarding the content accuracy and a policy for site review and revision.</p>
    <h3>Accessibility</h3>
    <p>The Georgia portal strives to comply with accessibility standards developed as part of the Web Access Initiative of the World Wide Web Consortium available at http://www.w3.org/WAI/. However, the Digital Library of Georgia does not guarantee that sites linked to by the portal will comply with these accessibility standards.</p>
    <h3>Removal Policy</h3>
    <p>A site may be removed from the Georgia Portal at the discretion of the Digital Library of Georgia for one or more of the following:</p>
    <ul>
      <li>Site is not consistently available and reliable</li>
      <li>Inaccurate data, facts, or information</li>
      <li>Proven violation of copyright</li>
      <li>Site or content is no longer available for free to the public</li>
    </ul>
    <p>July, 2001<br />Revised September 2004<br />Revised February 2018</p>
  </div>
</section>