config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new

  resources :solr_document, only: [:show], path: '/record', controller: 'records' do
    concerns :exportable
    get 'fulltext', to: 'records#fulltext'
    get 'presentation/manifest', to: 'records#presentation_manifest'
    get 'harmful_content', to: 'records#harmful_content'
  end

  resource :records, only: %i[index show] do
    get 'map', to: 'map', as: 'map'
    concerns :searchable
    concerns :range_searchable
    collection do
      get 'suggest/:facet_name', to: 'records#suggest', as: 'suggest_facet', defaults: { format: 'json' }
    end
  end

  # so related routes are available with the *_catalog_url that BL expects in addition to *_record_url
  resource :records, only:[], as: :catalog do
    concerns :searchable
  end

  get '/collection/:collection_record_id', to: 'records#index', as: 'collection_home'

  if FeatureFlags.enabled? :serials
    get '/serial/:serial_record_id', to: 'records#index', as: 'serial_home'
  else
    get '/serial/:serial_record_id', to: redirect {|path_params, _request|
      TemporaryRedirectService.legacy_route_for_serial(path_params[:serial_record_id])
    }
  end
  get '/serials/:serial_record_id', to: redirect('/serial/%{serial_record_id}')

  resource :collections, only: [:index] do
    get 'map', to: 'map', as: 'map'
    concerns :searchable
    concerns :range_searchable
    member do
      get(
        '/:collection_record_id/:collection_resource_slug',
        to: 'collection_resources#show',
        as: 'collection_resource'
      )
    end
  end

  resource :serials, only: %i[index] do
    concerns :searchable
    concerns :range_searchable
  end

  get '/collections/:collection_slug', to: 'records#index'

  resource :institutions, only: %i[index], path: '/institutions(/:first_char)', first_char: /[a-zA-Z]|0-9/, controller: 'institutions' do
    concerns :searchable
  end

  resources :institution_solr_documents, only: [:show], path: '/institutions/', controller: 'institutions' do
    concerns :exportable
  end

  resources :collection_solr_documents, only: [:show], path: '/collections/', controller: 'collections' do
    concerns :exportable
  end

  resources :serial_solr_documents, only: [:show], path: '/serials/', controller: 'serials' do
    concerns :exportable
  end

  get '/search', to: 'advanced#index', as: 'search'
  get '/counties', to: 'counties#index', as: 'counties'

  get '/iiif-viewer', to: 'iiif_viewer#iiif_viewer', as: 'iiif_viewer'
  get '/iiif-embeddable', to: 'iiif_viewer#embeddable_iiif_viewer', as: 'embeddable_iiif_viewer'

  resources :bookmarks do
    concerns :exportable
    collection do
      delete 'clear'
    end
  end

  namespace :teach do
    get 'using-materials'
  end

  namespace :participate do
    get 'contribute'
    get 'nominate'
    get 'harmful_content'
    get 'partner-services'
    post 'nomination'
  end

  namespace :about do
    get 'mission'
    get 'policy'
    get 'partners-sponsors'
    get 'api'
    get 'harmful-content'
    get 'harmful-content-form'
    post 'harmful_content_submit'
  end

  namespace :help do
    get 'search'
    get 'refine-items'
    get 'refine-collections'
    get 'map'
  end

  get '/contact(/:formtype)', to: 'contact#index', formtype: /|dlg|crdl|ghnp/, as: 'contact'

  get '/id::record_id', to: redirect('/record/%{record_id}'), status: 301

  get '/*do_tag', do_tag: /do(?:-[a-z0-9-]+)?:[a-z0-9,_-]+/, to: redirect { |path_params, _req|
    if (m=path_params[:do_tag].match /^do(?<alt>-[a-z0-9-]+)?:(?<record_id>[a-z0-9,_-]+)$/)
      "https://dlg.galileo.usg.edu/do#{m[:alt]}:#{m[:record_id]}"
    end
  }

  root to: 'homepage#index'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/controllers/participate_controller.rb
# frozen_string_literal: true

# "Participate" menu item static page controller
class ParticipateController < HomepageController
  before_action :form_options, only: %i[nominate nomination]

  def contribute; end

  def nominate; end

  def nomination
    mail = NominationMailer.nomination_submission nominate_params
    sent = if mail.respond_to? :deliver_now
             mail.deliver_now
           else
             mail.deliver
           end
    respond_to do |format|
      format.html do
        if sent
          flash[:notice] = I18n.t('mail.nomination.status.sent')
        else
          flash[:error] = I18n.t('mail.nomination.status.failed')
        end
        redirect_to participate_nominate_path
      end
    end
  end

  def partner_services; end

  def promotional_materials; end

  private

  def form_options
    @form_options = {}
    @form_options[:types] = [
      ['Manuscript (handwritten documents, letters, etc.)', 'MSS'],
      ['Typescript (typewritten documents)', 'Typescript'],
      ['Book'], ['Maps/Broadsides/Posters'], ['Pamphlet'],
      ['Photographs'], ['Audio'], ['Video'], ['Other']
    ]
  end

  def nominate_params
    params.permit(
      :collection_name,
      :repository_name,
      :repository_contact,
      :collection_type_details,
      :collection_information,
      :md_gil,
      :md_finding_aid,
      :md_other,
      :collection_metadata_other,
      :publication_status,
      :publication_status_details,
      :transcription_information,
      :nomination_reason,
      :restrictions,
      :preservation_concerns,
      :skills,
      :homeplace,
      :name,
      :address,
      :phone,
      :email,
      collection_types: []
    )
  end
end

app/views/participate/contribute.html.erb
<section id="participate">
  <div class="container-xl">
    <h1>Contribute Your Collections</h1>
    <p><%= link_to 'DLG\'s mission', about_mission_path %> includes supporting Georgia cultural heritage institutions with all aspects of the digitization cycle from selection to delivery. In addition, we host four portals (Georgia, Civil Rights, Civil War, and historic newspapers) and funnel metadata to the Digital Public Library of America.</p>
    <p>If you have existing digital projects and metadata to share, let us know using our <a href="https://forms.office.com/r/tQpcYMse5T" target="_blank">DLG Collection Harvesting Request form</a>. We are happy to ingest metadata that meets our <a href="https://docs.google.com/document/d/1LtCncs-uMcE4HRQzPuvXHcr9Is3Md223zmWz0shmB0w" target="_blank">minimum metadata guidelines</a> and can accept records via harvesting or spreadsheet submission. We are harvested by DPLA  quarterly (March, June, September, and December).</p>
    <p>Don’t have online collections yet? Here’s a quick summary of what you’ll need to consider before starting. We’re happy to help you get your project started.</p>
    <ol>
      <li><strong>PLAN</strong> - Think your library wants to digitize materials? Get an overview of the process before starting any project. Check out the <a href="https://sites.google.com/view/dlg-docs/resources/presentations-and-workshops/digitization" target="_blank">DLG's digitization resources</a>. Need help securing funds? Investigate <a href="https://sites.google.com/view/dlg-docs/resources/programs-and-projects/subgranting-program" target="_blank">DLG's Subgranting program</a> or consider partnering with us on a grant application. If your institution is a public library, consider working with <a href="https://georgialibraries.org/archival-services/" target="_blank">GPLS Archival Services and Digital Initiatives</a>.
      <li><strong>SELECT</strong> - Do you have historical materials that you'd like included in DLG? Check out our <%= link_to 'collection development policy', about_policy_path %> and <%= link_to 'nominate a collection', participate_nominate_path %> today. You may also need to <a href="https://docs.google.com/document/d/1p3TQDlYHlUKyUJR2zMPck23KzL5q8qpzupW1mMBXiuQ/edit?usp=sharing" target="_blank">get permission from copyright holders to display online</a>. Our <a href="https://docs.google.com/document/d/1p3TQDlYHlUKyUJR2zMPck23KzL5q8qpzupW1mMBXiuQ/edit?usp=sharing" target="_blank">Securing Permissions to Digitize and Display Collections Online document</a> includes form templates.
      <li><strong>CONVERT</strong> - DLG can help you with deciding how to digitize your materials -- partner with us, convert yourself, or work with a vendor. You'll want both master files and access files created. Check out our <a href="https://sites.google.com/view/dlg-docs/resources/presentations-and-workshops/digitization" target="_blank">digitization resources</a> to see our recommendations.
      <li><strong>DESCRIBE</strong> - Make your materials discoverable by creating metadata that conforms to DLG's <a href="https://goo.gl/BL4Q96" target="_blank">metadata guidelines</a>. Don't having the staffing or expertise? We can help.</li>
      <li><strong>HOST</strong> - Upload your access files to the Web. Need help with deciding what platform to use or need help hosting? Contact us to discuss hosting and display options with you.</li>
      <li><strong>PRESERVE</strong> - Make sure your project lasts over time by creating master files and storing them redundantly. Need assistance with archival storage? DLG can help. We provide limited free web and archival storage. See our <a href="https://docs.google.com/document/d/1OZjEg_IzSRjRq6Js7-UmaEPxHn58ZbfGMvCJ0BS4TMA">Service Cost Recovery list</a> for details.</li>
      <li><strong>SHARE</strong> - Promote your project by sharing metadata with DLG and the DPLA. If you've got collections already online, let us know by using our <a href="https://forms.office.com/r/tQpcYMse5T" target="_blank">notification form</a>. DPLA harvests quarterly.</li>
    </ol>
  </div>
</section>

app/views/participate/nominate.html.erb
<%= render partial: 'shared/flash_msg', layout: 'shared/flash_messages' %>
<section id="participate">
  <div class="container-xl">
    <h1><%= t('mail.nomination.title') %></h1>
    <p><%= t('mail.nomination.intro') %></p>
    <%= form_tag participate_nomination_path, method: :post %>
    <div class="form-group">
      <%= label_tag :collection_name, t('mail.nomination.questions.collection_name') %>
      <%= text_area_tag :collection_name, '', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :repository_name, t('mail.nomination.questions.repository_name') %>
      <%= text_area_tag :repository_name, '', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :repository_contact, t('mail.nomination.questions.repository_contact') %>
      <%= text_area_tag :repository_contact, '', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :collection_types, t('mail.nomination.questions.collection_types') %>
      <%= select_tag :collection_types, options_for_select(@form_options[:types]), multiple: true, class: 'form-control nomination-select' %>
    </div>
    <div class="form-group">
      <%= label_tag :collection_type_details, t('mail.nomination.questions.collection_type_details') %>
      <%= text_area_tag :collection_type_details, '', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :collection_information, t('mail.nomination.questions.collection_info') %>
      <%= text_area_tag :collection_information, '', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :collection_metadata, t('mail.nomination.questions.collection_metadata.label') %>
      <p><%= t('mail.nomination.questions.collection_metadata.question') %></p>
      <%= check_box_tag :md_gil, 'gil record' %>
      <%= label_tag :md_gil, t('mail.nomination.questions.collection_metadata.gil') %><br />
      <%= check_box_tag :md_finding_aid, 'finding aid' %>
      <%= label_tag :md_finding_aid, t('mail.nomination.questions.collection_metadata.finding_aid') %><br />
      <%= check_box_tag :md_other, 'other' %>
      <%= label_tag :md_other, t('mail.nomination.questions.collection_metadata.other') %>
    </div>
    <div class="form-group">
      <%= label_tag :collection_metadata_other, t('mail.nomination.questions.collection_metadata_other') %>
      <%= text_area_tag :collection_metadata_other, '', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :publication_status, t('mail.nomination.questions.publication_status.label') %>
      <p><%= t('mail.nomination.questions.publication_status.question') %></p>
      <%= radio_button_tag :publication_status, 'published' %>
      <%= label_tag :publication_status_published, t('mail.nomination.questions.publication_status.published') %>
      <%= radio_button_tag :publication_status, 'unpublished' %>
      <%= label_tag :publication_status_unpublished, t('mail.nomination.questions.publication_status.unpublished') %>
    </div>
    <div class="form-group">
      <%= label_tag :publication_status_details, t('mail.nomination.questions.publication_status_details') %>
      <%= text_area_tag :publication_status_details, '', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :transcription_information, t('mail.nomination.questions.transcription_information') %>
      <%= text_area_tag :transcription_information, '', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :nomination_reason, t('mail.nomination.questions.nomination_reason') %>
      <%= text_area_tag :nomination_reason, '', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :restrictions, t('mail.nomination.questions.restrictions') %>
      <%= text_area_tag :restrictions, '', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :preservation_concerns, t('mail.nomination.questions.preservation_concerns') %>
      <%= text_area_tag :preservation_concerns, '', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :skills, t('mail.nomination.questions.skills') %>
      <%= text_area_tag :skills, '', class: 'form-control' %>
    </div>
    <div class="form-group">
      <p><%= t('mail.nomination.questions.homeplace') %></p>
      <%= check_box_tag :homeplace %>
      <%= label_tag :homeplace, 'Yes' %>
    </div>
    <div class="form-group">
      <%= label_tag :name, t('mail.nomination.questions.name') %>
      <%= text_field_tag :name, '', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :address, t('mail.nomination.questions.address') %>
      <%= text_area_tag :address, '', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :phone, t('mail.nomination.questions.phone') %>
      <%= phone_field_tag :phone, '', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :email, t('mail.nomination.questions.email') %>
      <%= email_field_tag :email, '', class: 'form-control' %>
    </div>
    <%= submit_tag t('mail.nomination.questions.submit'), class: 'btn btn-primary' %>
  </div>
</section>

app/views/participate/partner_services.html.erb
<section id="participate">
  <div class="container-xl">
    <h1>Services For Partners</h1>
    <p>
      DLG provides more than just access to digitized content from Georgia Libraries, Archives and Museums. As part of our mission to support digitization efforts in the state, DLG provides its partners a number of services for free or cost recovery fees. We also provide a <a href="https://goo.gl/Ua4S4n">quarterly newsletter</a> and <a href="https://forms.gle/Lwx2LvLcTonrjL8QA">listserv</a> to keep our partners apprised of new initiatives and offerings.
    </p>
    <div class="row">
      <div class="col-lg-6">
        <div class="row">
          <div class="col-lg-12">
            <h2>Free Services</h2>
          </div>
          <div class="col-lg-12">
            <ul>
              <li><a href="https://sites.google.com/view/DLG-Docs">Best practice guides and toolkits</a></li>
              <li>Consulting</li>
              <li>Grant proposal development assistance</li>
              <li>Hosting of access or master files</li>
              <li>Metadata funneling to DPLA</li>
              <li>Metadata hosting</li>
              <li>Metadata harvesting/ingest</li>
              <li><a href="https://goo.gl/Ua4S4n">Quarterly newsletter</a></li>
              <li><a href="https://sites.google.com/view/dlg-docs/resources/programs-and-projects/subgranting-program">Subgranting</a></li>
              <li>Training (on-site and virtual)</li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="row">
          <div class="col-lg-12">
            <h2><a href="https://docs.google.com/document/d/1OZjEg_IzSRjRq6Js7-UmaEPxHn58ZbfGMvCJ0BS4TMA">Cost Recovery</a></h2>
          </div>
          <div class="col-lg-12">
            <ul>
              <li>Conversion</li>
              <li>Digital preservation</li>
              <li>Metadata creation</li>
              <li>Hosting of finding aid databases</li>
              <li><a href="https://sites.google.com/view/dlg-docs/resources/programs-and-projects/archivesspace-hosting-pilot">Hosting of ArchivesSpace</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <p>
      <img src="<%= asset_path 'collab-graph.jpg' %>" alt="DLG Services flowchart" class="img-responsive pull-right">
      For each project, DLG works with its partners to determine how to best divide and conquer the various tasks in a successful digital project. Together, we take a look at your infrastructure: expertise, staffing levels, and technology to determine the right fit. For some of DLG's bigger partners, we simply aggregate their metadata to include in one of our portals and eventually as part of DPLA. For others, such as public libraries, DLG carries much more of the workload. We even work with vendors for conversion.
    </p>
    <p>
      Don't see a service that you need or want? Take a few minutes to fill out our <a href="https://docs.google.com/forms/d/e/1FAIpQLSdB9PztFHaDx6_Rmf3nALP7NH-CvLes4VmeQcYyQfz4rxXgCQ/viewform?usp=sf_link">partner services survey</a>.
    </p>
  </div>
</section>